#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
news:
  path: /usuario/
  defaults: { _controller: 'App\Controller\UsuarioController::news' }
  methods:  [GET]

loginUser:
  path: /login/
  controller: 'App\Controller\CheckUserController::login'
  methods:  [GET]