#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
news:
  path: /usuario/
  defaults: { _controller: 'App\Controller\UsuarioController::news' }
  methods:  [POST]

loginUser:
  path: /login/
  controller: 'App\Controller\CheckUserController::login'
  methods:  [POST]

newEvento:
  path: /crearevento/
  controller: 'App\Controller\EventoController::index'
  methods:  [POST]

allEvents:
   path: /GetAllEvents/
   controller: 'App\Controller\EventoController::allEventos'
   methods:  [GET]