#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
news:
  path: /usuario/
  defaults: { _controller: 'App\Controller\UsuarioController::news' }
  methods:  [GET]

loginUser:
  path: /login/
  controller: 'App\Controller\CheckUserController::login'
  methods:  [GET]

newEvento:
  path: /crearevento/
  controller: 'App\Controller\EventoController::createEvent'
  methods:  [GET]

allEvents:
   path: /getAllEvents/
   controller: 'App\Controller\EventoController::getallEvent'
   methods:  [GET]

findUser:
   path: /getUser/
   controller: 'App\Controller\UsuarioController::findUser'
   methods:  [GET]

getUser:
   path: /User/
   controller: 'App\Controller\UsuarioController::getAll'
   methods:  [GET]

getMembers:
   path: /getAllMembers/
   controller: 'App\Controller\EventoController::getAllMembers'
   methods:  [GET]

deleteuser:
   path: /deleteUser/
   controller: 'App\Controller\UsuarioController::deleteUser'
   methods:  [GET]

deleteevent:
   path: /deleteEvent/
   controller: 'App\Controller\EventoController::deleteEvent'
   methods:  [GET]

deletemember:
   path: /deleteMember/
   controller: 'App\Controller\EventoController::deleteMember'
   methods:  [GET]

setmembermessege:
   path: /setMemberMessage/
   controller: 'App\Controller\EventoController::setMemberMessage'
   methods:  [GET]

setmembermessegenull:
   path: /setMemberMessageNull/
   controller: 'App\Controller\EventoController::setMemberMessageNull'
   methods:  [GET]

seteventmessege:
   path: /setEventMessage/
   controller: 'App\Controller\EventoController::setEventMessage'
   methods:  [GET]
