#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
news:
  path: /usuario/
  defaults: { _controller: 'App\Controller\UsuarioController::news' }
  methods:  [POST]

loginUser:
  path: /login/
  controller: 'App\Controller\CheckUserController::login'
  methods:  [POST]

newEvento:
  path: /crearevento/
  controller: 'App\Controller\EventoController::createEvent'
  methods:  [GET]

allEvents:
   path: /getAllEvents/
   controller: 'App\Controller\EventoController::getallEvent'
   methods:  [GET]

findUser:
   path: /getUser/
   controller: 'App\Controller\UsuarioController::findUser'
   methods:  [GET]