#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }
news:
  path: /usuario/
  defaults: { _controller: 'App\Controller\UsuarioController::news' }
  methods:  [GET]